#define DEFAULT_TIME_UNIT_IN_NANOS 100
#define DEFAULT_TIMER_QUEUE_TIMER_COUNT 32
#define DEFAULT_MAX_FRAME_QUEUE_SIZE_PER_TRACK 60
#define DEFAULT_FRAME_RATE 24
#define DEFAULT_DEVICE_NAME_LEN 16
#define DEFAULT_STREAM_NAME_LEN 16
#define DEFAULT_TIMECODE_SCALE_SENTINEL 0
#define DEFAULT_LOGGER_LOG_LEVEL LOG_LEVEL_WARN
#define DEFAULT_VIDEO_TRACK_ID 1
#define DEFAULT_AUDIO_TRACK_ID 2
#define DEFAULT_ENDPOINT_CACHE_UPDATE_PERIOD (40 * HUNDREDS_OF_NANOS_IN_A_MINUTE)
#define DEFAULT_KVS_CACERT_PATH EMPTY_STRING
#define DEFAULT_LOW_SPEED_LIMIT 30
#define DEFAULT_LOW_SPEED_TIME_LIMIT (30 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define DEFAULT_SSL_PORT_NUMBER 443
#define DEFAULT_NON_SSL_PORT_NUMBER 8080
#define DEFAULT_CALLBACK_CHAIN_COUNT 5
#define LOG_LEVEL_VERBOSE 1
#define LOG_LEVEL_DEBUG 2
#define LOG_LEVEL_INFO 3
#define LOG_LEVEL_WARN 4
#define LOG_LEVEL_ERROR 5
#define LOG_LEVEL_FATAL 6
#define LOG_LEVEL_SILENT 7
#define FRAME_CURRENT_VERSION 0
